### ISSUE TITLE
black square issue qt5

### ISSUE THREAD

**Issue by marlemion** [maliit/plugins#8]
Hi,

I have been running qt4 maliit on my wetab using arch for some time now (0.94-qt4 branch). As kde is approaching the 5 version, I would like to prepare for the switch. So I compiled maliit-frameworks, maliit-plugins and maliit-inputcontext-qt4 and installed it accordingly. It is running, however, there are some glitches.

All sources are master from this git repository

frameworks
qmake -qt=5 -r . MALIIT_DEFAULT_PLUGIN=libmaliit-keyboard-plugin.so CONFIG+="qt5-inputcontext notests nodoc" && make
plugins
qmake -qt=5 -r . CONFIG+="debug enable-hunspell enable-presage notests nodoc" && make
inputcontext-qt4
qmake-qt4 -r .

1) black square

there is a black square in the middle of each of the styles available for libmaliit-plugins.so.. nemo-keyboard does not have this problem, but other issues (see 2). I heavily amended the corresponding qml files - no way to get rid of it. Is this proble known? I cannot reach the keys, which are covered by this square.

2) orientation

if I access windows drawn by qt4, everything works fine (ecept the square). However, qt5-windows let the keyboard appear with a reduced width (libmaliit-plugin.so). If I use the nemo-keyboard, the keyboard even is rotated to the right side of the screen. There is no workng accelerometer in the wetab, so this is sole magic of the maliit code. I saw a recent commit dedicated to orientation, maybe that messed it up. I helped myself by copying the landscape values in main.ini to the respective portrait values, but that's a very ugly hack.

3) cpu usage and usability

Cpu usage is quite high on the dual-core atom. It is about 50-60%. The animations are bad, most of them aren't actually visible as they are too slow. This was significantly faste with the 0.94-qt4 version. Possibly this is faster again, if the switch to a pure qt5 desktop has been entirely performed.

4) word prediction

...is not working. It used to work with the 0.94-qt4 branch. However, the word-ribbon is not popping up at all.

I would like to help with these issues. I would also provide screen shots if necessary. Right now, maliit cannot be considered to be a working platform for qt5 based systems. I know that there are nearly no maintainers left, but it would be sad to lose this nice piece of software from the free software world.

**Comment by jpetersen** [comment]
I agree it needs some work to get ready again with current Qt 5.

1) That is probably the QQuickView of the extended keyboard panel maliit-keyboard-extended.qml. The window handling code seems to be quite buggy (see inputmethod.cpp).

Note that this code was written for some specific platform (some years ago) and probably needs adaption for other use cases.

2) Yes probably needs some debugging

3) I actually do not know how we do animations. Since Qt 5.2 we have the Animator classes which could help here: http://doc.qt.io/qt-5/qml-qtquick-animator.html

4) I fear the word-ribbon bar is not implemented in QML yet

**Comment by marlemion** [comment]
Hey,

unfortunately I have moved away from Maliit when Arch switched to Plasma 5. However as regards 2) I can tell you that the accelerometer is actually working with recent kernels and I can even use it for rotating my screen. Maybe QT5 somehow uses it by default.

**Comment by dobey** [comment]
Closing this now as this repo has been superseded by maliit-keyboard, and should be archived.
